// alt_e100s10_sys_pll.v

// Generated using ACDS version 19.1 240

`timescale 1 ps / 1 ps
module alt_e100s10_sys_pll (
		input  wire  rst,      //   reset.reset
		input  wire  refclk,   //  refclk.clk
		output wire  locked,   //  locked.export
		output wire  outclk_0  // outclk0.clk
	);

	alt_e100s10_sys_pll_altera_iopll_191_7krab4i alt_e100s10_sys_pll_inst (
		.rst      (rst),      //   input,  width = 1,   reset.reset
		.refclk   (refclk),   //   input,  width = 1,  refclk.clk
		.locked   (locked),   //  output,  width = 1,  locked.export
		.outclk_0 (outclk_0)  //  output,  width = 1, outclk0.clk
	);

endmodule
